const employeeMock = [
    {
        firstName: 'John',
        lastName: 'Doe',
        startDate: '2021-01-01',
        department: 'IT',
        dateOfBirth: '1990-06-15',
        street: '123 Main St',
        city: 'Anytown',
        state: 'NY',
        zipCode: '12345',
    },
    {
        firstName: 'Jane',
        lastName: 'Doe',
        startDate: '2020-03-10',
        department: 'HR',
        dateOfBirth: '1988-04-22',
        street: '456 Elm St',
        city: 'Somewhere',
        state: 'CA',
        zipCode: '67890',
    },
    {
        firstName: 'Bob',
        lastName: 'Smith',
        startDate: '2019-11-20',
        department: 'Finance',
        dateOfBirth: '1980-10-05',
        street: '789 Maple Dr',
        city: 'Nowhere',
        state: 'TX',
        zipCode: '11223',
    },
    {
        firstName: 'Alice',
        lastName: 'Smith',
        startDate: '2022-02-15',
        department: 'Sales',
        dateOfBirth: '1987-12-20',
        street: '666 Oak Ln',
        city: 'Everywhere',
        state: 'CA',
        zipCode: '99999',
    },
]
export default employeeMock;