const employeeMock = [
    {
        firstName: 'Linus',
        lastName: 'Torvalds',
        startDate: '1991-08-25',
        department: 'Kernel Engineering',
        dateOfBirth: '1969-12-28',
        street: '15 Penguin Way',
        city: 'Helsinki',
        state: 'FI',
        zipCode: '12345',
    },
    {
        firstName: 'Ada',
        lastName: 'Lovelace',
        startDate: '1833-07-04',
        department: 'Programming',
        dateOfBirth: '1815-12-10',
        street: '846 Engine Ln',
        city: 'London',
        state: 'GB',
        zipCode: '67890',
    },
    {
        firstName: 'Grace',
        lastName: 'Hopper',
        startDate: '1943-12-09',
        department: 'Computer Science',
        dateOfBirth: '1906-12-09',
        street: '42 Bug-Free Blvd',
        city: 'New York',
        state: 'NY',
        zipCode: '11223',
    },
    {
        firstName: 'Alan',
        lastName: 'Turing',
        startDate: '1936-01-20',
        department: 'Cryptanalysis',
        dateOfBirth: '1912-06-23',
        street: '3 Codebreaker St',
        city: 'Cambridge',
        state: 'GB',
        zipCode: '99999',
    },
    {
        firstName: 'John',
        lastName: 'Doe',
        startDate: '1995-05-15',
        department: 'Software Development',
        dateOfBirth: '1978-09-17',
        street: '555 Example Rd',
        city: 'Los Angeles',
        state: 'CA',
        zipCode: '54321',
    },
    {
        firstName: 'Jane',
        lastName: 'Smith',
        startDate: '2000-11-30',
        department: 'Web Design',
        dateOfBirth: '1985-03-21',
        street: '607 Creative Ave',
        city: 'San Francisco',
        state: 'CA',
        zipCode: '98765',
    },
    {
        firstName: 'Michael',
        lastName: 'Johnson',
        startDate: '2010-03-10',
        department: 'Network Administration',
        dateOfBirth: '1990-02-05',
        street: '74 Network Ln',
        city: 'Chicago',
        state: 'IL',
        zipCode: '76543',
    },
    {
        firstName: 'Emily',
        lastName: 'Williams',
        startDate: '2015-08-22',
        department: 'Data Analysis',
        dateOfBirth: '1993-12-12',
        street: '133 Data Rd',
        city: 'Houston',
        state: 'TX',
        zipCode: '23456',
    },
    {
        firstName: 'David',
        lastName: 'Brown',
        startDate: '2007-06-14',
        department: 'Database Management',
        dateOfBirth: '1982-07-30',
        street: '9 Database St',
        city: 'Miami',
        state: 'FL',
        zipCode: '34567',
    },
    {
        firstName: 'Sophia',
        lastName: 'Davis',
        startDate: '2018-04-05',
        department: 'Software Development',
        dateOfBirth: '1996-01-25',
        street: '90 Dev Rd',
        city: 'Seattle',
        state: 'WA',
        zipCode: '87654',
    },
    {
        firstName: 'William',
        lastName: 'Miller',
        startDate: '2004-02-28',
        department: 'Security Analysis',
        dateOfBirth: '1980-09-03',
        street: '51 Security Ln',
        city: 'Dallas',
        state: 'TX',
        zipCode: '45678',
    },
    {
        firstName: 'Olivia',
        lastName: 'Smith',
        startDate: '2012-11-17',
        department: 'Network Engineering',
        dateOfBirth: '1991-05-14',
        street: '12 Network Rd',
        city: 'Phoenix',
        state: 'AZ',
        zipCode: '56789',
    },
    {
        firstName: 'Ethan',
        lastName: 'Brown',
        startDate: '2009-09-08',
        department: 'System Administration',
        dateOfBirth: '1984-03-28',
        street: '13 System St',
        city: 'Denver',
        state: 'CO',
        zipCode: '67890',
    },
    {
        firstName: 'Mia',
        lastName: 'Davis',
        startDate: '2016-07-03',
        department: 'Data Science',
        dateOfBirth: '1994-08-18',
        street: '140 Data Rd',
        city: 'Atlanta',
        state: 'GA',
        zipCode: '78901',
    },
    {
        firstName: 'James',
        lastName: 'Johnson',
        startDate: '2008-12-12',
        department: 'Programming',
        dateOfBirth: '1983-11-10',
        street: '440 Code Rd',
        city: 'Austin',
        state: 'TX',
        zipCode: '12345',
    },
    {
        firstName: 'Emma',
        lastName: 'Jones',
        startDate: '2013-10-19',
        department: 'Web Development',
        dateOfBirth: '1992-04-29',
        street: '16 Web Rd',
        city: 'San Diego',
        state: 'CA',
        zipCode: '23456',
    },
    {
        firstName: 'Alexander',
        lastName: 'Martin',
        startDate: '2011-06-06',
        department: 'Database Administration',
        dateOfBirth: '1981-07-15',
        street: '5 DB Rd',
        city: 'Las Vegas',
        state: 'NV',
        zipCode: '34567',
    },
    {
        firstName: 'Ava',
        lastName: 'Smith',
        startDate: '2017-05-24',
        department: 'Security Analysis',
        dateOfBirth: '1995-02-22',
        street: '2514 Security Ln',
        city: 'Portland',
        state: 'OR',
        zipCode: '45678',
    },
    {
        firstName: 'Noah',
        lastName: 'Lee',
        startDate: '2014-09-07',
        department: 'System Administration',
        dateOfBirth: '1993-03-15',
        street: '99 System St',
        city: 'San Jose',
        state: 'CA',
        zipCode: '56789',
    },
    {
        firstName: 'Oliver',
        lastName: 'Clark',
        startDate: '2019-02-14',
        department: 'Data Analysis',
        dateOfBirth: '1997-10-08',
        street: '201 Data Rd',
        city: 'Raleigh',
        state: 'NC',
        zipCode: '67890',
    },
];

export default employeeMock;
