const employeeMock = [
    {
        firstName: 'Linus',
        lastName: 'Torvalds',
        startDate: '1991-08-25',
        department: 'Kernel Engineering',
        dateOfBirth: '1969-12-28',
        street: '1 Penguin Way',
        city: 'Helsinki',
        state: 'FI',
        zipCode: '12345',
    },
    {
        firstName: 'Ada',
        lastName: 'Lovelace',
        startDate: '1833-07-04',
        department: 'Programming',
        dateOfBirth: '1815-12-10',
        street: '2 Analytical Engine Ln',
        city: 'London',
        state: 'GB',
        zipCode: '67890',
    },
    {
        firstName: 'Grace',
        lastName: 'Hopper',
        startDate: '1943-12-09',
        department: 'Computer Science',
        dateOfBirth: '1906-12-09',
        street: '3 Bug-Free Blvd',
        city: 'New York',
        state: 'NY',
        zipCode: '11223',
    },
    {
        firstName: 'Alan',
        lastName: 'Turing',
        startDate: '1936-01-20',
        department: 'Cryptanalysis',
        dateOfBirth: '1912-06-23',
        street: '4 Codebreaker St',
        city: 'Cambridge',
        state: 'GB',
        zipCode: '99999',
    },
]
export default employeeMock;
